### ISSUE TITLE
ios build fail by PGB

### ISSUE THREAD

**Issue by bau720123** [disusered/cordova-open#22]
hi @disusered 
I am using PGB 3.7 with your latest plugin 1.0.2 version
http://plugins.cordova.io/#/package/com.disusered.open

but when I use you plugin
it will build fail that only in iOS (Android and winphone build ok)

**Comment by bau720123** [comment]
so....strange
problem solved...

**Comment by disusered** [comment]
@bau720123 glad to hear it was sorted!
