### ISSUE TITLE
not wrok in PGB's 3.7 with Android and iOS

### ISSUE THREAD

**Issue by bau720123** [disusered/cordova-open#23]
not wrok in PGB's 3.7 with Android and iOS
it will occur a wrong message
http://www.littlebau.com/open01.jpg

**Comment by disusered** [comment]
Ok I will take a look.

**Comment by disusered** [comment]
It looks like the core File plugin is missing. File-Transfer should have it as its dependency, but with the change in the plugin system it seems to be failing. I added the dependency to `org.apache.cordova.file` directly, so hopefully it will work for your case!

**Comment by bau720123** [comment]
hi @disusered 
I use the 1.0.4 version
http://plugins.cordova.io/#/package/com.disusered.open
but still occur the sane situation

by the way
I am using....
org.apache.cordova.file-transfer => 0.5.0
http://plugins.cordova.io/#/package/org.apache.cordova.file-transfer
org.apache.cordova.file => 1.3.3
http://plugins.cordova.io/#/package/org.apache.cordova.file

**Comment by disusered** [comment]
@bau720123 Ok, I normally use the latest Cordova, I will try to reproduce with Phonegap.

**Comment by bau720123** [comment]
really thanks for @disusered help

**Comment by bau720123** [comment]
hi @disusered 
is there anything update or ....

**Comment by disusered** [comment]
Hi @bau720123 I had to go to my home town to visit an ill family member, I will try to look at it in the next few days. Sorry!

**Comment by bau720123** [comment]
Hi @disordered
okok，really thanks a lot

**Comment by bau720123** [comment]
hi @disusered 
just want to ask
is there anything update ?

**Comment by disusered** [comment]
I am finally back home, I will look into your issue and some others brought up soon.

**Comment by bau720123** [comment]
got it
thanks @disusered

**Comment by disusered** [comment]
I'm very sorry but I was unable to replicate the issue. I tested with the latest Phonegap, not 3.7. Perhaps try older versions of the plugin, but the truth is I have personal projects on Cordova and test against newer versions of it. Given my time and work constraints, I can't commit to supporting legacy versions of wrappers around Cordova such as Phonegap or CCA.

Best of luck and sorry I could not be of more help.

![screen shot 2015-04-26 at 11 14 17 am](https://cloud.githubusercontent.com/assets/246254/7338065/85054224-ec05-11e4-91e0-f64ae6ae0719.png)
![screen shot 2015-04-26 at 11 15 01 am](https://cloud.githubusercontent.com/assets/246254/7338066/8506e2dc-ec05-11e4-9477-1f59b6b7df32.png)
