### ISSUE TITLE
which one is the true ? (latest)

### ISSUE THREAD

**Issue by bau720123** [disusered/cordova-open#26]
hi @disusered 
I saw two plugins's author is you
http://plugins.cordova.io/#/package/com.bridge.open
http://plugins.cordova.io/#/package/com.disusered.open
these two plugins look like all the same

so...which one is the true ? (latest)
"com.bridge.open" or "com.disusered.open" ?

**Comment by disusered** [comment]
com.disusered.open is the latest, I deprecated the other.

**Comment by bau720123** [comment]
thanks @disusered
