### ISSUE TITLE
Not work in Android 4.2.9

### ISSUE THREAD

**Issue by pig2** [disusered/cordova-open#29]
Hi,
I built it locally by Phonegap 3.3 and installed APP to real device.
No APP selection menu showed. No callback showed.
Could you provide sample app in Github?
THX.

**Comment by disusered** [comment]
I test against Cordova, the script for creating the project is [here](https://github.com/disusered/cordova-open/blob/develop/bin/dependencies.sh), just ignore the last two commands that install the tests. There is also a script for building, [here](https://github.com/disusered/cordova-open/blob/develop/bin/install.sh). I will create a sample app and update the thread when done, most likely tomorrow.

**Comment by disusered** [comment]
I am unable to replicate the issue. See #30 for a solution.
