### ISSUE TITLE
not work in android

### ISSUE THREAD

**Issue by sirius007** [disusered/cordova-open#31]
var open = cordova.plugins.bridge.open;
          function success() {
              console.log('Success');
          }

          function error(code) {
              if (code === 1) {
                  console.log('No file handler found');
              } else {
                  console.log('Undefined error');
              }
          }

          open('http://git-scm.com/images/logo@2x.png', success, error);
      };

242418   error    ReferenceError: FileTransfer is not defined
    at downloadAndOpen (http://192.168.0.128:8100/plugins/com.bridge.open/www/bridge.open.js:41:16)
    at http://192.168.0.128:8100/plugins/com.bridge.open/www/bridge.open.js:25:5

**Comment by disusered** [comment]
The plugin depends on [cordova-file-transfer](https://github.com/apache/cordova-plugin-file-transfer) for network requests. It should be installed automatically, if not then you'd have to add it: `cordova plugin add cordova-plugin-file-transfer` and it should work!

**Comment by sirius007** [comment]
i have add it :cordova plugin add cordova-plugin-file-transfer , but i doesn't work, some idea

**Comment by sirius007** [comment]
cordova plugin add cordova-plugin-file-transfer

**Comment by disusered** [comment]
Does it give the same error? Are you using Cordova, Phonegap, something
else?  Try the plugin with a local file first. If not look at the tests,
there are examples there.

On Sun, Aug 2, 2015 at 7:56 PM, sirius007 <notifications@github.com> wrote:

> cordova plugin add cordova-plugin-file-transfer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/disusered/cordova-open/issues/31#issuecomment-127092714>
> .
>



-- 
Carlos
