### ISSUE TITLE
events are not destroyed

### ISSUE THREAD

**Issue by PedroJusto** [disusered/cordova-open#39]
if my success callback only logs "File opened successfully", when I open one file for the third time, it will log "File opened successfully" 3 times and PDF will open 3 times

**Comment by disusered** [comment]
I'm having some difficulties getting the plugin working with the latest cordova. As soon as I work out those kinks I will look at what's up with events, sorry.

**Comment by PedroJusto** [comment]
Thanks I'll look forward for an answer from you

**Comment by disusered** [comment]
This was addressed by @sfrank87 via https://github.com/disusered/cordova-open/pull/52 🙌
