### ISSUE TITLE
Get the OK event and nothing happens

### ISSUE THREAD

**Issue by cmorgado** [disusered/cordova-open#46]
I'm using the plug in after downloading a file

  var open = cordova.plugins.disusered.open;

```
                            open(entry.toURL()
                                , function() {
                                    console.log("ok"); 

                                }
                                , function (code) {
                                    console.log("kok: " + code);

                            });
```

I get the OK but nothing happens either in the emulator or device...

Any clues on how to debug this?

**Comment by mladenp** [comment]
Yup, i got same problem, in iOS only, Android works fine.
I tried passing url parameter with "file:/" and without, no luck

**Comment by disusered** [comment]
This was addressed by @sfrank87 via https://github.com/disusered/cordova-open/pull/52 🙌
