### ISSUE TITLE
The plugin no longer work on iOS 10 beta (14A5346a)

### ISSUE THREAD

**Issue by sidlauskaslukas** [disusered/cordova-open#48]
The app crashes immediately when you try to open the file. The app crashes at this line in the Open.m file:

    [self.viewController presentViewController:previewCtrl animated:YES completion:nil];

And this is what I get in the console during the crash:

    bool _WebTryThreadLock(bool), 0x1700178b0: Tried to obtain the web lock from a thread other       than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

**Comment by sidlauskaslukas** [comment]
I fixed this in this pull request #49

**Comment by disusered** [comment]
Thank you very much! I merged into `develop` I will cut a release in the next day or two.
