### ISSUE TITLE
Create a new release for latest fixes please

### ISSUE THREAD

**Issue by Catscratch** [disusered/cordova-open#50]
Hi,

can you please create a new release and push it to npm repository?

Thanks!

**Comment by Mark-Leck** [comment]
As above...Hoping this will solve IOS10 crash when opening file.

**Comment by disusered** [comment]
Pushed the update, thank you for the contributions!

**Comment by dcz-switcher** [comment]
How can I get the new release ?
Your last commit failed
https://travis-ci.org/disusered/cordova-open/builds/161165355

regards

**Comment by disusered** [comment]
I have not updated the CI script but the fix was tested by others and works, so it was published despite the breaking build.

1.0.10:
- https://github.com/disusered/cordova-open/releases
- https://www.npmjs.com/package/cordova-open
