### ISSUE TITLE
Black screen on iOS8 when closing file that was opened

### ISSUE THREAD

**Issue by SebastianSchirmer** [disusered/cordova-open#54]
On iOS8, when opening a file using the plugin and closing it again clicking "Done" in the upper left, I am getting a black screen and my app is not usable anymore. I've tried to debug it without success yet.

Therefore, anyone experiencing the same issue or maybe has a hint for debugging?

**Comment by Owlbertz** [comment]
I have the same issue. Anyone with a solution?

**Comment by SebastianSchirmer** [comment]
We have not analyzed this further and decided not to support iOS 8 anymore going forward. Therefore this issue is not an issue for us anymore.

**Comment by Owlbertz** [comment]
I currently experience the issue for iOS11 also (despite the screen being blank/white and not black). Do you have and idea what version of the plugin started causing the issue?
And was it resolved by updating to a higher iOS version while keeping the same (buggy) version of the plugin?

**Comment by SebastianSchirmer** [comment]
We had this issue only with iOS 8. iOS 9 and up were working fine. However, we've switched to another plugin as we had other issues using this plugin on Android. We're now using cordova-plugin-file-opener2 instead which is working fine for us.

**Comment by Owlbertz** [comment]
I will have a look into that, thanks a lot!

**Comment by SebastianSchirmer** [comment]
Good luck, you're welcome

**Comment by SebastianSchirmer** [comment]
I am closing this issue as we have switched to using cordova-plugin-file-opener2 instead of this plugin.
